---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: api
  namespace: bring-it
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - api.bring-it.thuault.com
    secretName: api-bring-it-tls
  rules:
  - host: api.bring-it.thuault.com
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: 8080
